
name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v2
        with:
          project: Project Automation
          column: Todo
          repo-token: ${{ secrets.TOKEN }}
