name: Move Card to Todo
on:
  issues:
    types: [ assigned ]
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: fojia/action-move-issues-to-column@master
        with:
          project: 'Project Automation'
          column: 'Todo'
          github_token: ${{ secrets.TOKEN }}
